name: workflow2

on:
  push:
    branches:
       - main
  pull_request:
     branches:
      - main
  
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: step 2
        run: |
         ls -l
         echo "github repo name is ${{GITHUB.REPOSITIORY}} and branch name is ${{ GITHUB.REF_NAME}}"
         pwd
